### ISSUE TITLE
some images are imported as childImageSharp, some are not

### ISSUE THREAD

**Issue by catalina-cimpanu** [strapi/gatsby-source-strapi#157]
I am working on a project gatsby-strapi. 
I updated strapi with `npm update` and it broke my project (because you actually have to migrate). 
In order to solve this, I created a new strapi, where I recreated all the content types, and I got the data from the database that I already had. 
Except, since then, my gatsby project breaks, because now all the images for my blog posts are not imported as childImageSharp (which was the case before), and I only have url :

![blogpost](https://user-images.githubusercontent.com/67892765/97084019-5835a600-1614-11eb-9a8f-b2aa1273ee0a.png)

On the other side, I have other categories for which I CAN import the childImageSharp:

![pathology-with-ImageSharp](https://user-images.githubusercontent.com/67892765/97084081-c1b5b480-1614-11eb-9865-9eed524d911b.png)
And all this is very,very ironical because the reason I updated in the first place was that I wasn't able to import the svgs correctly for these pathologies! 

I tried to create a new category, articles, but I have the exact same problem:

![article](https://user-images.githubusercontent.com/67892765/97084170-5d472500-1615-11eb-86b8-f22fa146d336.png)

Is there any solution for this?  I will anyway try to go back to the last git commit that worked, but I think it's just such a pity :(

Thank you in advance for your help

My system:
Node.js version: v12.18.3
NPM version: 6.14.8
Strapi version: 3.2.5
Database: mongoDB (Atlas)
Operating system: Windows10

**Comment by kuntal-ghosh** [comment]
Did you find any solution for that?

**Comment by rroslaniec** [comment]
I got same issue - there is solution: https://github.com/strapi/gatsby-source-strapi/issues/98#issuecomment-582492769

**Comment by torquan** [comment]
I have the same problem with components in single files.
While the solution in #98 works for one component, I can't
add resolvers for every component.. There are far too many.

If I query the images through allImageSharp or allFile, I can get the imageSharp Nodes.
The "original name" of the images are pretty cryptic though, i.e. "1c2c1b54482eea1a21f1e3e5337d5751.png"
And I'd like to query through the component.

Another workaround that seems to be working would be to query upload/files from Strapi, as then I'd have only
one directory, meaning only one resolver.

Any other solutions how to get imageSharp nodes on images sourced from strapi?

**Comment by torquan** [comment]
To explain my problem better:

```
 strapiFactFile {
    singleMediaField {
       childImageSharp {
        id //works
      }
    }
    aComponent {
      SingleMediaFieldTwo {
        id //works
        childrenImageSharp //error
      }
    }
  }
```

Is this a problem with the plugin or on my side?

**Comment by torquan** [comment]
I'm not able to fix this, but perhaps this might help:

- With the plugin installed through npm, images in components are of type "Strapi[...]". You can't query the local file.
- Images outside of components are of type "File". You can query childImageSharp here.

Now I replaced the package files with my own build (I changed nothing). Then, it looks different:
- Images outside of components are of type "Strapi[..][FieldName] and DO have a property "localFile" through which you can access imageSharp
- Images inside of components behave exactly the same.

It seems there is a problem with the packing of the package (?). Unfortunately, I've no idea about that or how to even get the processed files that I find in node_modules. The build command of this package only copies them to /dist.

I'll probably use a fork to fix this, otherwise, I'll update the package and it'll stop working again...

**Comment by remidej** [comment]
Hello, we're aware of this issue, but let's keep discussing it on #98 instead
