### ISSUE TITLE
How to get cloudinary url on queries using gatsby-source-strapi

### ISSUE THREAD

**Issue by rifqirosyidi** [strapi/gatsby-source-strapi#186]
Hi,

I have strapi app with strapi-provider-upload-cloudinary, and seems it works fine. the image URL changes to `res.cloudinary ....`, this is in production of course. when i try to query for example https://mywebsite.com/articles. this will list all the articles and if that article contains an image the URL automatically replaced by Cloudinary URL.

![image](https://user-images.githubusercontent.com/41833714/113697633-a986ad00-96fd-11eb-8c35-37004fe90d9a.png)

how can I get the Cloudinary URL using Graphql request in allStrapiArticles on gatsby-source-strapi? for now when I try to query those image it always points to '/static instead of Cloudinary, I already tried on both development and production environment, it returns /static, 

![image](https://user-images.githubusercontent.com/41833714/113697320-3d0bae00-96fd-11eb-87b3-6e2ddcb45ca9.png)

for the example above i already using the strapi host url, not http://localhost:1337 anymore, can anyone help how to get the cloudinary url on gatsby-source-strapi?

**Comment by wereallmonks** [comment]
This is due to the way your images are configured. The images are being sent to a static folder through gatsby-source-filesystem in your config file. I believe you would have to use the cloudinary plugin in order to query the images to use the cloudinary url, but since the cloudinary is an added plugin in your Strapi, the file-system in gatsby is adding it to a static file.
