### ISSUE TITLE
Dynamic zone is JSON instead of Node

### ISSUE THREAD

**Issue by FredWahlqvistDrop** [strapi/gatsby-source-strapi#191]
When implementing the latest alpha version to implement dynamic zones  all teh data in the dynamic zone is interpenetrated as a JSON string instead of a Node object, this stops me from using Gatsby image plugin etc on images in dynamic zones. 

Any quidence on how to get around this?

**Comment by phmasek** [comment]
I am experiencing the same issue. Did you find any solution around this?

**Comment by remidej** [comment]
Hello, this is a choice we made on purpose for the new v1.0.0

The problem is that Gatsby used to try to merge all the components in a dynamic zone as a single node type. That made it impossible to query only the right fields for each component in a dynamic zones. It also made it impossible to use GraphQL fragments for each component. And if several of your DZ components had some fields with the same name, it would fail entirely. In other words, the dynamic zone support was broken.

So we chose a different approach for this new version, which is to rely on the JSON scalar, instead of a node. But it's true that a big tradeoff is the lack of image optimization in dynamic zones.

We're hoping we can add better support for dynamic zones without using JSON in the future. But that requires a very big rewrite of the schema generation, and right now we needed a quick fix rather than a long change. But we know that we'll need to release a new major version later this year when Strapi V4 launches. I'm hoping we can use this opportunity for breaking changes to improve dynamic zones.
