### ISSUE TITLE
Question: i18n / proper configuration changes

### ISSUE THREAD

**Issue by Leviathan91** [strapi/gatsby-source-strapi#201]
Hi everyone, I was wondering if my planned changes are correct.
My currently working relevant part of the config:
  ```
options: {
        // Strapi content types
        contentTypes: ['Blogs', 'Testemonials'],
        singleTypes: ['Privacy-Statement', 'Imprint'],
      },
```

and my planned changes:

```
options: {
        // Strapi content types
        contentTypes: [
          {
            name: 'Blogs',
            api: { qs: { _locale: CURRENT_LANGUAGE } },
          },
          {
            name: 'Testemonials',
            api: { qs: { _locale: CURRENT_LANGUAGE } },
          },
        ],
        singleTypes: ['Privacy-Statement', 'Imprint'],
      },
    },
```
    
   If I do it this way, do I still have to add the "locale" filter to the given query string in my components or is this enough?
   Right now it crashes, but I guess that is because it has not been released yet, right?

**Comment by 8byr0** [comment]
You're right, it has not been released yet (https://github.com/strapi/gatsby-source-strapi/issues/192#issuecomment-831233249)!

In current version, the plugin only returns the default language entries. Let's say you've got english(default) and french, gatsby gql will only be query english entities. 
With the new version that'll be released, both french and english will be available for querying (if you've configured your type to do so) but you'll need to pass the locale filter to your component query if you want to display only entries in a given language. Otherwise all entries will be returned.

**Comment by Leviathan91** [comment]
That is what I was asking about. The way I wrote the config I thought it is already only fetching the current locale, and therefore I do not have to modify the component queries?
Or what is the point of  using the new api-->qs-->_locale syntax, If I have to specify the locale in my query anway?   
I feel like I haven't fully understood it.

**Comment by remidej** [comment]
Hello @Leviathan91 

Can you try with the latest plugin release, and let me know if everything works as expected? You can find config examples on the readme
