### ISSUE TITLE
accessToken has NO effect

### ISSUE THREAD

**Issue by creative-ae** [strapi/gatsby-source-strapi#294]
Im trying to use accessToken in the strapi config as per the doc:
```
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});

const strapiConfig = {
  apiURL: process.env.STRAPI_API_URL,
  accessToken: process.env.STRAPI_TOKEN, 
  collectionTypes: ['article', 'company', 'author'],
  singleTypes: [],
};

module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-strapi`,
      options: strapiConfig,
    },
  ],
};
```
however, the plugin is completely ignoring the accessToken. So i checked the source code of the plugin. and found out that in `lib/index.js` it tries to get an access token using "identifier/password" rest call. and there is NO consideration if the JWT already passed in the options. the code is 

`const jwtToken = await (0, _authentication.default)({
    loginData,
    reporter,
    apiURL
  });`

if there is no loginData in the options, authentication will return JjwtToken as null. 

so in order to accessToken option work, i had to modify the `lib/index.js` as follows:

```
...
...
{
  apiURL = 'http://localhost:1337',
  loginData = {},
  queryLimit = 100,
  accessToken = null, // <--- added accessToken as const here
  ...options
})
....
....
  const jwtToken = accessToken || await (0, _authentication.default)({   // <---- if accessToken is in the options then use it, else fall to the login method
    loginData,
    reporter,
    apiURL
  });
...
...
```
and after that it works like a charm. but this is a workaround/patch. this issue should be fixed in the plugin

**Comment by remidej** [comment]
The login method was used in version v1.x of gatsby-source-strapi, which was only compatible with Strapi v3. The new 2.0.0 release removed it to use API tokens instead (a new Strapi v4 feature). Both are not supposed to coexist.

If you're using a 2.x.x release and the accessToken doesn't work, make sure that:

- It's a **full-access** API token. Read-only isn't enough
- Your environment variable is correctly picked up in the gatsby-config file. You can try to log it to ensure that.
- Your API token is correct. You may want to re-generate one to make sure of that

> So i checked the source code of the plugin. and found out that in lib/index.js it tries to get an access token using "identifier/password" rest call

Based on your PR (#295), it looks like you looked at the v4 branch. Unfortunately that branch was an old POC that we should have deleted earlier. The "identifier/password" call was deleted since. The code for the 2.x.x release that supports Strapi v4 is on the master branch.

Let me know if these checks don't fix your problem, I'll reopen the issue if needed.

**Comment by creative-ae** [comment]
Im confused !! when i follow the readme file, i get v 1.0.3. and thats what i was commenting on, and now u mentioned that we need version 2.x.x. so i tried to install the latest beta (2.0.0-beta.0), but no matter what i do, i always get `Error: Request failed with status code 403`. please advice

**Comment by remidej** [comment]
No we don't have any plans to go back to the JWT/login approach. I think what could make this possible in the future would be if we make the API token feature more modular in Strapi itself. But I don't think there's any plans for that either

**Comment by creative-ae** [comment]
Thanks for quick reply, i guess the full Access API token is required to get all the content types available in Strapi, 

so i ended giving permissions to the authenticated user role to be able to get `/api/content-type-builder/content-types` and `api/content-type-builder/components`, then in Strapi, i limit the API response to those APIs based on the calling source (to prevent the user getting such info). 

And Voila. the user JWT worked out. and able to get the user data only based on the JWT
