### ISSUE TITLE
using ___NODE is deprecated

### ISSUE THREAD

**Issue by laurenskling** [strapi/gatsby-source-strapi#297]
This source uses `___NODE` a lot. It's deprecated and should not be used:

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#___node-convention-is-deprecated

**Comment by soupette** [comment]
@laurenskling we are planning on using the `createSchemaCustomization` API but the `___NODE` won't be deprecated until Gatsby v5 and maybe v6 so we still have time to migrate.

I am closing this issue feel free to either reopen it or maybe open a pull request in order to implement the new API?

If you are into contributing to the project feel free to reach out to us so we can walk you through how to implement the new API.
