### ISSUE TITLE
API token required when public access is available

### ISSUE THREAD

**Issue by carstenblt** [strapi/gatsby-source-strapi#302]
With the strapi v3 version this plugin was usable without an access token, when public access to a collection was enabled. It's not clear to me, why this is now required.

**Comment by remidej** [comment]
Hello, I understand why this seems odd, but this is the expected behavior.

The API token is required because the plugin now [fetches data](https://github.com/strapi/gatsby-source-strapi/blob/058c23c121f8c1cbf8f197f1782922edfaac250e/src/fetch.js#L16-L17) from the content-type-builder API, which has restricted access. We also plan on using this API more in the future to generate the Gatsby graphql schema.

Another small benefit is that you only have to to set the access token once, to have access to everything. On v3 you had to enable the permissions for each content type in the settings.
